# Generated by Django 4.0.4 on 2022-06-06 05:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='asdas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo_main',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
